# Generated by Django 3.2.10 on 2023-08-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('cover', models.CharField(max_length=200)),
                ('Cemail', models.EmailField(blank=True, max_length=100, null=True)),
                ('Resume', models.FileField(blank=True, null=True, upload_to='applicantresume')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='companydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eemail', models.CharField(max_length=200)),
                ('Ename', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Nature', models.CharField(max_length=200)),
                ('Enumber', models.CharField(max_length=200)),
                ('Founded', models.CharField(max_length=200)),
                ('Contact', models.CharField(max_length=200)),
                ('Cemail', models.EmailField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='Logo')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Documentation', models.FileField(blank=True, null=True, upload_to='Companydoc')),
                ('Website', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employerregdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jobpostdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.IntegerField(blank=True, null=True)),
                ('empid', models.IntegerField(blank=True, null=True)),
                ('Title', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Cemail', models.EmailField(blank=True, max_length=100, null=True)),
                ('Type', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Experiance', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=100)),
                ('Requirement', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(max_length=200)),
                ('Date', models.DateField(auto_now_add=True)),
                ('approval', models.CharField(default='pending', max_length=100)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
