# Generated by Django 3.2.10 on 2023-09-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_auto_20230830_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerregdb',
            old_name='Password',
            new_name='PAssword',
        ),
    ]
