# Generated by Django 3.2.10 on 2023-09-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_rename_password_employerregdb_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerregdb',
            old_name='PAssword',
            new_name='Password',
        ),
    ]
