# Generated by Django 3.2.10 on 2023-08-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_employerregdb_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobpostdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('vaccancy', models.CharField(max_length=100)),
                ('Experiance', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
    ]
