# Generated by Django 3.2.10 on 2023-08-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_jobpostdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostdb',
            old_name='vaccancy',
            new_name='Location',
        ),
    ]
