# Generated by Django 3.2.10 on 2023-08-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20230817_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantregdb',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='applicantregdb',
            old_name='Password',
            new_name='password',
        ),
    ]
