# Generated by Django 3.2.10 on 2023-08-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20230817_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applicationdb',
        ),
    ]
