# Generated by Django 3.2.10 on 2023-08-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20230828_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofiledb',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
