# Generated by Django 3.2.10 on 2023-09-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_enquirydb'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantregdb',
            name='status',
            field=models.CharField(default='ok', max_length=100),
        ),
    ]
