# Generated by Django 3.2.10 on 2023-09-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_applicantregdb_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantregdb',
            old_name='password',
            new_name='Password',
        ),
    ]
